#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Only run tests when pushing to develop or main
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" = "develop" ] || [ "$current_branch" = "main" ]; then
  echo "Running tests before push to $current_branch..."
  pnpm test:unit
fi
